// <auto-generated />
using System;
using Air_3550.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(AirContext))]
    [Migration("20210421170749_ATLSeeding")]
    partial class ATLSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Air_3550.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Elevation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("Decimal(8,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("Decimal(9,6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirportId");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            AirportId = 1,
                            City = "Cleveland",
                            Code = "CLE",
                            Elevation = 791,
                            Latitude = 41.411667m,
                            Longitude = -81.849722m,
                            State = "Ohio"
                        },
                        new
                        {
                            AirportId = 2,
                            City = "Nashville",
                            Code = "BNA",
                            Elevation = 599,
                            Latitude = 36.126667m,
                            Longitude = -86.681944m,
                            State = "Tennessee"
                        },
                        new
                        {
                            AirportId = 3,
                            City = "Detroit",
                            Code = "DTW",
                            Elevation = 645,
                            Latitude = 42.2125m,
                            Longitude = -83.353333m,
                            State = "Michigan"
                        },
                        new
                        {
                            AirportId = 4,
                            City = "Atlanta",
                            Code = "ATL",
                            Elevation = 1026,
                            Latitude = 33.636667m,
                            Longitude = -84.428056m,
                            State = "Georgia"
                        },
                        new
                        {
                            AirportId = 5,
                            City = "New York City",
                            Code = "LGA",
                            Elevation = 21,
                            Latitude = 40.775m,
                            Longitude = -73.875m,
                            State = "New York"
                        },
                        new
                        {
                            AirportId = 6,
                            City = "Los Angeles",
                            Code = "LAX",
                            Elevation = 128,
                            Latitude = 33.9425m,
                            Longitude = -118.408056m,
                            State = "California"
                        },
                        new
                        {
                            AirportId = 7,
                            City = "Chicago",
                            Code = "MDW",
                            Elevation = 668,
                            Latitude = 41.786111m,
                            Longitude = -87.7525m,
                            State = "Illinois"
                        },
                        new
                        {
                            AirportId = 8,
                            City = "Dallas",
                            Code = "DFW",
                            Elevation = 607,
                            Latitude = 32.896944m,
                            Longitude = -97.038056m,
                            State = "Texas"
                        },
                        new
                        {
                            AirportId = 9,
                            City = "Denver",
                            Code = "DEN",
                            Elevation = 5434,
                            Latitude = 39.861667m,
                            Longitude = -104.673056m,
                            State = "Colorado"
                        },
                        new
                        {
                            AirportId = 10,
                            City = "Seattle",
                            Code = "SEA",
                            Elevation = 433,
                            Latitude = 47.448889m,
                            Longitude = -122.309444m,
                            State = "Washington"
                        });
                });

            modelBuilder.Entity("Air_3550.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerDataId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Air_3550.Models.CustomerData", b =>
                {
                    b.Property<int>("CustomerDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RewardPointsBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardPointsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerDataId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerDatas");
                });

            modelBuilder.Entity("Air_3550.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.HasIndex("PlaneId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            DepartureTime = new TimeSpan(0, 6, 35, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 1,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 2,
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 2,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 3,
                            DepartureTime = new TimeSpan(0, 12, 35, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 3,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 4,
                            DepartureTime = new TimeSpan(0, 15, 30, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 4,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 5,
                            DepartureTime = new TimeSpan(0, 9, 45, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 5,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 6,
                            DepartureTime = new TimeSpan(0, 12, 30, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 6,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 7,
                            DepartureTime = new TimeSpan(0, 15, 45, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 7,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 8,
                            DepartureTime = new TimeSpan(0, 18, 30, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 8,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 9,
                            DepartureTime = new TimeSpan(0, 8, 15, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 9,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 10,
                            DepartureTime = new TimeSpan(0, 11, 30, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 10,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 11,
                            DepartureTime = new TimeSpan(0, 14, 15, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 11,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 12,
                            DepartureTime = new TimeSpan(0, 17, 15, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 12,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 13,
                            DepartureTime = new TimeSpan(0, 11, 15, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 13,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 14,
                            DepartureTime = new TimeSpan(0, 14, 30, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 14,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 15,
                            DepartureTime = new TimeSpan(0, 17, 15, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 15,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 16,
                            DepartureTime = new TimeSpan(0, 20, 15, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 16,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 17,
                            DepartureTime = new TimeSpan(0, 15, 15, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 17,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 18,
                            DepartureTime = new TimeSpan(0, 18, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 18,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 19,
                            DepartureTime = new TimeSpan(0, 21, 15, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 19,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 20,
                            DepartureTime = new TimeSpan(0, 0, 15, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 20,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 21,
                            DepartureTime = new TimeSpan(0, 12, 15, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 21,
                            OriginAirportId = 4,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 22,
                            DepartureTime = new TimeSpan(0, 15, 30, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 22,
                            OriginAirportId = 4,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 23,
                            DepartureTime = new TimeSpan(0, 18, 15, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 23,
                            OriginAirportId = 4,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 24,
                            DepartureTime = new TimeSpan(0, 21, 15, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 24,
                            OriginAirportId = 4,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 25,
                            DepartureTime = new TimeSpan(0, 17, 5, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 25,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 26,
                            DepartureTime = new TimeSpan(0, 20, 35, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 26,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 27,
                            DepartureTime = new TimeSpan(0, 23, 5, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 27,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 28,
                            DepartureTime = new TimeSpan(0, 2, 35, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 28,
                            OriginAirportId = 1,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 29,
                            DepartureTime = new TimeSpan(0, 14, 5, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 29,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 30,
                            DepartureTime = new TimeSpan(0, 17, 35, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 30,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 31,
                            DepartureTime = new TimeSpan(0, 20, 5, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 31,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 32,
                            DepartureTime = new TimeSpan(0, 23, 35, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 32,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 33,
                            DepartureTime = new TimeSpan(0, 11, 15, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 33,
                            OriginAirportId = 1,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 34,
                            DepartureTime = new TimeSpan(0, 14, 45, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 34,
                            OriginAirportId = 1,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 35,
                            DepartureTime = new TimeSpan(0, 17, 15, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 35,
                            OriginAirportId = 1,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 36,
                            DepartureTime = new TimeSpan(0, 20, 45, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 36,
                            OriginAirportId = 1,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 37,
                            DepartureTime = new TimeSpan(0, 14, 15, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 37,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 38,
                            DepartureTime = new TimeSpan(0, 17, 45, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 38,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 39,
                            DepartureTime = new TimeSpan(0, 20, 15, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 39,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 40,
                            DepartureTime = new TimeSpan(0, 23, 45, 0, 0),
                            DestinationAirportId = 1,
                            IsCanceled = false,
                            Number = 40,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 41,
                            DepartureTime = new TimeSpan(0, 13, 40, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 41,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 42,
                            DepartureTime = new TimeSpan(0, 16, 10, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 42,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 43,
                            DepartureTime = new TimeSpan(0, 19, 40, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 43,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 44,
                            DepartureTime = new TimeSpan(0, 22, 10, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 44,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 45,
                            DepartureTime = new TimeSpan(0, 16, 40, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 45,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 46,
                            DepartureTime = new TimeSpan(0, 19, 10, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 46,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 47,
                            DepartureTime = new TimeSpan(0, 22, 40, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 47,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 48,
                            DepartureTime = new TimeSpan(0, 1, 10, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 48,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 49,
                            DepartureTime = new TimeSpan(0, 14, 0, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 49,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 50,
                            DepartureTime = new TimeSpan(0, 17, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 50,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 51,
                            DepartureTime = new TimeSpan(0, 20, 0, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 51,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 52,
                            DepartureTime = new TimeSpan(0, 23, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 52,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 53,
                            DepartureTime = new TimeSpan(0, 11, 0, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 53,
                            OriginAirportId = 4,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 54,
                            DepartureTime = new TimeSpan(0, 14, 30, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 54,
                            OriginAirportId = 4,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 55,
                            DepartureTime = new TimeSpan(0, 17, 0, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 55,
                            OriginAirportId = 4,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 56,
                            DepartureTime = new TimeSpan(0, 20, 30, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 56,
                            OriginAirportId = 4,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 57,
                            DepartureTime = new TimeSpan(0, 9, 45, 0, 0),
                            DestinationAirportId = 5,
                            IsCanceled = false,
                            Number = 57,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 58,
                            DepartureTime = new TimeSpan(0, 12, 15, 0, 0),
                            DestinationAirportId = 5,
                            IsCanceled = false,
                            Number = 58,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 59,
                            DepartureTime = new TimeSpan(0, 15, 45, 0, 0),
                            DestinationAirportId = 5,
                            IsCanceled = false,
                            Number = 59,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 60,
                            DepartureTime = new TimeSpan(0, 18, 15, 0, 0),
                            DestinationAirportId = 5,
                            IsCanceled = false,
                            Number = 60,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 61,
                            DepartureTime = new TimeSpan(0, 6, 45, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 61,
                            OriginAirportId = 5,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 62,
                            DepartureTime = new TimeSpan(0, 9, 15, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 62,
                            OriginAirportId = 5,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 63,
                            DepartureTime = new TimeSpan(0, 12, 45, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 63,
                            OriginAirportId = 5,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 64,
                            DepartureTime = new TimeSpan(0, 15, 15, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 64,
                            OriginAirportId = 5,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 65,
                            DepartureTime = new TimeSpan(0, 6, 30, 0, 0),
                            DestinationAirportId = 6,
                            IsCanceled = false,
                            Number = 65,
                            OriginAirportId = 2,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 66,
                            DepartureTime = new TimeSpan(0, 9, 0, 0, 0),
                            DestinationAirportId = 6,
                            IsCanceled = false,
                            Number = 66,
                            OriginAirportId = 2,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 67,
                            DepartureTime = new TimeSpan(0, 12, 30, 0, 0),
                            DestinationAirportId = 6,
                            IsCanceled = false,
                            Number = 67,
                            OriginAirportId = 2,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 68,
                            DepartureTime = new TimeSpan(0, 15, 0, 0, 0),
                            DestinationAirportId = 6,
                            IsCanceled = false,
                            Number = 68,
                            OriginAirportId = 2,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 69,
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 69,
                            OriginAirportId = 6,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 70,
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 70,
                            OriginAirportId = 6,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 71,
                            DepartureTime = new TimeSpan(0, 15, 30, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 71,
                            OriginAirportId = 6,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 72,
                            DepartureTime = new TimeSpan(0, 18, 0, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 72,
                            OriginAirportId = 6,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 73,
                            DepartureTime = new TimeSpan(0, 6, 0, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 73,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 74,
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 74,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 75,
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 75,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 76,
                            DepartureTime = new TimeSpan(0, 15, 30, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 76,
                            OriginAirportId = 2,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 77,
                            DepartureTime = new TimeSpan(0, 6, 0, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 77,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 78,
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 78,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 79,
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 79,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 80,
                            DepartureTime = new TimeSpan(0, 15, 30, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 80,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 81,
                            DepartureTime = new TimeSpan(0, 7, 45, 0, 0),
                            DestinationAirportId = 8,
                            IsCanceled = false,
                            Number = 81,
                            OriginAirportId = 2,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 82,
                            DepartureTime = new TimeSpan(0, 10, 15, 0, 0),
                            DestinationAirportId = 8,
                            IsCanceled = false,
                            Number = 82,
                            OriginAirportId = 2,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 83,
                            DepartureTime = new TimeSpan(0, 13, 45, 0, 0),
                            DestinationAirportId = 8,
                            IsCanceled = false,
                            Number = 83,
                            OriginAirportId = 2,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 84,
                            DepartureTime = new TimeSpan(0, 16, 45, 0, 0),
                            DestinationAirportId = 8,
                            IsCanceled = false,
                            Number = 84,
                            OriginAirportId = 2,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 85,
                            DepartureTime = new TimeSpan(0, 10, 45, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 85,
                            OriginAirportId = 8,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 86,
                            DepartureTime = new TimeSpan(0, 13, 15, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 86,
                            OriginAirportId = 8,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 87,
                            DepartureTime = new TimeSpan(0, 16, 45, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 87,
                            OriginAirportId = 8,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 88,
                            DepartureTime = new TimeSpan(0, 19, 15, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 88,
                            OriginAirportId = 8,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 89,
                            DepartureTime = new TimeSpan(0, 5, 40, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 89,
                            OriginAirportId = 2,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 90,
                            DepartureTime = new TimeSpan(0, 8, 10, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 90,
                            OriginAirportId = 2,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 91,
                            DepartureTime = new TimeSpan(0, 11, 40, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 91,
                            OriginAirportId = 2,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 92,
                            DepartureTime = new TimeSpan(0, 14, 10, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 92,
                            OriginAirportId = 2,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 93,
                            DepartureTime = new TimeSpan(0, 8, 40, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 93,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 94,
                            DepartureTime = new TimeSpan(0, 11, 10, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 94,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 95,
                            DepartureTime = new TimeSpan(0, 14, 40, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 95,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 96,
                            DepartureTime = new TimeSpan(0, 17, 10, 0, 0),
                            DestinationAirportId = 2,
                            IsCanceled = false,
                            Number = 96,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 97,
                            DepartureTime = new TimeSpan(0, 7, 5, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 97,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 98,
                            DepartureTime = new TimeSpan(0, 10, 45, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 98,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 99,
                            DepartureTime = new TimeSpan(0, 13, 5, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 99,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 100,
                            DepartureTime = new TimeSpan(0, 16, 45, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 100,
                            OriginAirportId = 3,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 101,
                            DepartureTime = new TimeSpan(0, 10, 5, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 101,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 102,
                            DepartureTime = new TimeSpan(0, 13, 45, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 102,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 103,
                            DepartureTime = new TimeSpan(0, 16, 5, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 103,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 104,
                            DepartureTime = new TimeSpan(0, 19, 45, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 104,
                            OriginAirportId = 7,
                            PlaneId = 1
                        },
                        new
                        {
                            FlightId = 105,
                            DepartureTime = new TimeSpan(0, 16, 30, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 105,
                            OriginAirportId = 3,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 106,
                            DepartureTime = new TimeSpan(0, 19, 0, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 106,
                            OriginAirportId = 3,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 107,
                            DepartureTime = new TimeSpan(0, 22, 30, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 107,
                            OriginAirportId = 3,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 108,
                            DepartureTime = new TimeSpan(1, 1, 0, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 108,
                            OriginAirportId = 3,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 109,
                            DepartureTime = new TimeSpan(0, 13, 30, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 109,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 110,
                            DepartureTime = new TimeSpan(0, 16, 0, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 110,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 111,
                            DepartureTime = new TimeSpan(0, 19, 30, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 111,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 112,
                            DepartureTime = new TimeSpan(0, 22, 0, 0, 0),
                            DestinationAirportId = 3,
                            IsCanceled = false,
                            Number = 112,
                            OriginAirportId = 9,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 113,
                            DepartureTime = new TimeSpan(0, 7, 0, 0, 0),
                            DestinationAirportId = 5,
                            IsCanceled = false,
                            Number = 113,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 114,
                            DepartureTime = new TimeSpan(0, 10, 30, 0, 0),
                            DestinationAirportId = 5,
                            IsCanceled = false,
                            Number = 114,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 115,
                            DepartureTime = new TimeSpan(0, 13, 0, 0, 0),
                            DestinationAirportId = 5,
                            IsCanceled = false,
                            Number = 115,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 116,
                            DepartureTime = new TimeSpan(0, 16, 30, 0, 0),
                            DestinationAirportId = 5,
                            IsCanceled = false,
                            Number = 116,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 117,
                            DepartureTime = new TimeSpan(0, 10, 0, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 117,
                            OriginAirportId = 5,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 118,
                            DepartureTime = new TimeSpan(0, 13, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 118,
                            OriginAirportId = 5,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 119,
                            DepartureTime = new TimeSpan(0, 16, 0, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 119,
                            OriginAirportId = 5,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 120,
                            DepartureTime = new TimeSpan(0, 19, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 120,
                            OriginAirportId = 5,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 121,
                            DepartureTime = new TimeSpan(0, 14, 45, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 121,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 122,
                            DepartureTime = new TimeSpan(0, 17, 15, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 122,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 123,
                            DepartureTime = new TimeSpan(0, 20, 45, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 123,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 124,
                            DepartureTime = new TimeSpan(0, 23, 15, 0, 0),
                            DestinationAirportId = 7,
                            IsCanceled = false,
                            Number = 124,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 125,
                            DepartureTime = new TimeSpan(0, 14, 45, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 125,
                            OriginAirportId = 7,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 126,
                            DepartureTime = new TimeSpan(0, 17, 15, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 126,
                            OriginAirportId = 7,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 127,
                            DepartureTime = new TimeSpan(0, 20, 45, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 127,
                            OriginAirportId = 7,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 128,
                            DepartureTime = new TimeSpan(0, 23, 15, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 128,
                            OriginAirportId = 7,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 129,
                            DepartureTime = new TimeSpan(0, 16, 0, 0, 0),
                            DestinationAirportId = 8,
                            IsCanceled = false,
                            Number = 129,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 130,
                            DepartureTime = new TimeSpan(0, 19, 30, 0, 0),
                            DestinationAirportId = 8,
                            IsCanceled = false,
                            Number = 130,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 131,
                            DepartureTime = new TimeSpan(0, 22, 0, 0, 0),
                            DestinationAirportId = 8,
                            IsCanceled = false,
                            Number = 131,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 132,
                            DepartureTime = new TimeSpan(0, 1, 30, 0, 0),
                            DestinationAirportId = 8,
                            IsCanceled = false,
                            Number = 132,
                            OriginAirportId = 4,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 133,
                            DepartureTime = new TimeSpan(0, 13, 0, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 133,
                            OriginAirportId = 8,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 134,
                            DepartureTime = new TimeSpan(0, 16, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 134,
                            OriginAirportId = 8,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 135,
                            DepartureTime = new TimeSpan(0, 19, 0, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 135,
                            OriginAirportId = 8,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 136,
                            DepartureTime = new TimeSpan(0, 22, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 136,
                            OriginAirportId = 8,
                            PlaneId = 2
                        },
                        new
                        {
                            FlightId = 137,
                            DepartureTime = new TimeSpan(0, 6, 30, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 137,
                            OriginAirportId = 4,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 138,
                            DepartureTime = new TimeSpan(0, 9, 0, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 138,
                            OriginAirportId = 4,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 139,
                            DepartureTime = new TimeSpan(0, 12, 30, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 139,
                            OriginAirportId = 4,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 140,
                            DepartureTime = new TimeSpan(0, 15, 0, 0, 0),
                            DestinationAirportId = 9,
                            IsCanceled = false,
                            Number = 140,
                            OriginAirportId = 4,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 141,
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 141,
                            OriginAirportId = 9,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 142,
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 142,
                            OriginAirportId = 9,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 143,
                            DepartureTime = new TimeSpan(0, 15, 30, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 143,
                            OriginAirportId = 9,
                            PlaneId = 3
                        },
                        new
                        {
                            FlightId = 144,
                            DepartureTime = new TimeSpan(0, 18, 0, 0, 0),
                            DestinationAirportId = 4,
                            IsCanceled = false,
                            Number = 144,
                            OriginAirportId = 9,
                            PlaneId = 3
                        });
                });

            modelBuilder.Entity("Air_3550.Models.Plane", b =>
                {
                    b.Property<int>("PlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlaneId");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            PlaneId = 1,
                            MaxDistance = 6570,
                            MaxSeats = 230,
                            Model = "Boeing 737 MAX"
                        },
                        new
                        {
                            PlaneId = 2,
                            MaxDistance = 14815,
                            MaxSeats = 416,
                            Model = "Boeing 747"
                        },
                        new
                        {
                            PlaneId = 3,
                            MaxDistance = 17395,
                            MaxSeats = 550,
                            Model = "Boeing 777"
                        });
                });

            modelBuilder.Entity("Air_3550.Models.ScheduledFlight", b =>
                {
                    b.Property<int>("ScheduledFlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduledFlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("ScheduledFlights");
                });

            modelBuilder.Entity("Air_3550.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduledFlightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ScheduledFlightId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Air_3550.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            LoginId = "accountant",
                            PasswordHash = "O+hVd5AIc4hngejP3jaUBHyJduXRk15reb/RyCkSY8wgBK6+AKe48n0LJ2UxVWY60NglI4NkfGRnKraWch8ftQ==",
                            Role = 1
                        },
                        new
                        {
                            UserId = 2,
                            LoginId = "load_engineer",
                            PasswordHash = "QewmDvo6oFSpHMbPlEHjZSY391lGyPpsLpJvKJ4JX0bmLhmijgL7D8Jd0Eex8E5uA8+TDUZLVAxAwARetrfiUg==",
                            Role = 2
                        },
                        new
                        {
                            UserId = 3,
                            LoginId = "flight_manager",
                            PasswordHash = "4iifPzpmqB9f+1Lf8aCc0q6Ro56ySCMNKQcIRnnGus20qIDaeDXKcgA9jDfhB8+Rxfl5VngwN1Trob5CA5v/TQ==",
                            Role = 3
                        },
                        new
                        {
                            UserId = 4,
                            LoginId = "marketing_manager",
                            PasswordHash = "NgyuvZ7baGCcCTO63jVlNQ5Z4oTMUDzmG/DuvUL7flvWV6ce0UmCJRaHV+fxCVkgQRzOJ3eeDHeOxSU13q4gQA==",
                            Role = 4
                        });
                });

            modelBuilder.Entity("Air_3550.Models.Booking", b =>
                {
                    b.HasOne("Air_3550.Models.CustomerData", null)
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerDataId");
                });

            modelBuilder.Entity("Air_3550.Models.CustomerData", b =>
                {
                    b.HasOne("Air_3550.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Air_3550.Models.Flight", b =>
                {
                    b.HasOne("Air_3550.Models.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Air_3550.Models.Airport", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Air_3550.Models.Plane", "Plane")
                        .WithMany()
                        .HasForeignKey("PlaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");

                    b.Navigation("Plane");
                });

            modelBuilder.Entity("Air_3550.Models.ScheduledFlight", b =>
                {
                    b.HasOne("Air_3550.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Air_3550.Models.Ticket", b =>
                {
                    b.HasOne("Air_3550.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Air_3550.Models.ScheduledFlight", "ScheduledFlight")
                        .WithMany()
                        .HasForeignKey("ScheduledFlightId");

                    b.Navigation("Booking");

                    b.Navigation("ScheduledFlight");
                });

            modelBuilder.Entity("Air_3550.Models.Booking", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Air_3550.Models.CustomerData", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
